"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ladyy.glb --transform 
Files: ladyy.glb [8.18MB] > C:\Users\akila\OneDrive\Desktop\Elthora\ladyy-transformed.glb [1.03MB] (87%)
*/

import React from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

import {
  bodyMaterial,
  clothMaterial,
  furnitureMaterial,
} from "@/utils/materials";

export default function LadyOnChair(props) {
  const { nodes, materials } = useGLTF("/ladyy-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={100}
        near={0.1}
        fov={24.051}
        position={[0.02, 0.15, 1.054]}
        rotation={[-0.033, 0.009, -0.017]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body_geo_face_0.geometry}
        // material={materials.face}
        position={[0.059, 0, 0.003]}
        scale={0.01}
      >
        {bodyMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.earring1_eye_0.geometry}
        // material={materials.material}
        position={[0.059, 0, 0.003]}
        scale={0.01}
      >
        {clothMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.jacket_geo_Female_Sitting_Posecloth1_0.geometry}
        // material={materials.Female_Sitting_Posecloth1}
        position={[0.059, 0, 0.003]}
        scale={0.01}
      >
        {clothMaterial}
      </mesh>
      {/* <mesh
			castShadow receiveShadow
				geometry={nodes.asset1_table1_0.geometry}
				material={materials.table1}
				position={[-0.066, -0.024, -0.001]}
				scale={0.013}
			/> */}
      {/* <mesh
			castShadow receiveShadow
				geometry={nodes.asset3_asset_0.geometry}
				material={materials.shoe1}
				position={[-0.056, -0.002, 0]}
				scale={0.01}
			/> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sofa_sofa2_0.geometry}
        // material={materials.sofa2}
        position={[0.203, 0, -0.013]}
        scale={0.01}
      >
        {furnitureMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1_shoe1_0.geometry}
        // material={materials.shoe1}
        position={[0.059, 0, 0.003]}
        scale={0.01}
      >
        {clothMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pant_geo_Female_Sitting_Posecloth1_0.geometry}
        // material={materials.Female_Sitting_Posecloth1}
        position={[0.059, 0, 0.003]}
        scale={0.01}
      >
        {clothMaterial}
      </mesh>
    </group>
  );
}

useGLTF.preload("/ladyy-transformed.glb");
