"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 looking_at_elthora.glb --transform 
Files: looking_at_elthora.glb [18.55MB] > C:\Users\akila\OneDrive\Desktop\Elthora\looking_at_elthora-transformed.glb [1.85MB] (90%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const bodyMaterial = (
  <meshPhysicalMaterial
    color="#c2c8ff"
    roughness={0.25}
    metalness={0.05}
    sheen={1}
    sheenColor="#ffffff"
    sheenRoughness={0.6}
    clearcoat={0.3}
    clearcoatRoughness={0.2}
    envMapIntensity={1}
    reflectivity={0.5}
  />
);
const clothMaterial = (
  <meshPhysicalMaterial
    color="#616ee0"
    roughness={0.25}
    metalness={0.05}
    sheen={1}
    sheenColor="#ffffff"
    sheenRoughness={0.6}
    clearcoat={0.3}
    clearcoatRoughness={0.2}
    envMapIntensity={1}
    reflectivity={0.5}
  />
);

export default function Model(props) {
  const { nodes, materials } = useGLTF("/looking_at_elthora-transformed.glb");
  return (
    <group {...props} dispose={null}>
      {/* wOMAN 1 */}
      {/* COAT */}
      <mesh
        geometry={nodes.defaultMaterial003.geometry}
        // material={materials.Woman1CoatMat}
        position={[0.776, -0.009, 1.334]}
        rotation={[0, -1.04, 0]}
        scale={0.554}
      >
        {clothMaterial}
      </mesh>
      {/* SKIN/FACE */}
      <mesh
        geometry={nodes.defaultMaterial004.geometry}
        // material={materials.Woman1Face}
        position={[0.776, -0.009, 1.334]}
        rotation={[0, -1.04, 0]}
        scale={0.554}
      >
        {bodyMaterial}
      </mesh>

      {/* MAN */}
      {/* CLOTH */}
      <mesh
        geometry={nodes.defaultMaterial043.geometry}
        // material={materials.ManClothes}
        position={[-0.031, 0.001, 1.367]}
        rotation={[0, -1.034, 0]}
        scale={1.49}
      >
        {clothMaterial}
      </mesh>
      {/* SKIN/FACE */}
      <mesh
        geometry={nodes.defaultMaterial042.geometry}
        position={[-0.031, 0.001, 1.367]}
        rotation={[0, -1.034, 0]}
        scale={1.49}
      >
        {bodyMaterial}
      </mesh>
      {/* HAIR */}
      <mesh
        geometry={nodes.defaultMaterial040.geometry}
        // material={materials.ManHair}
        position={[-0.031, 0.001, 1.367]}
        rotation={[0, -1.034, 0]}
        scale={1.49}
      >
        {clothMaterial}
      </mesh>

      {/* WOMAN 2 */}
      {/* CLOTH */}
      <mesh
        geometry={nodes.defaultMaterial022.geometry}
        // material={materials.Woman5Coat}
        position={[-0.95, 0.174, 1.021]}
        rotation={[0, 0.328, 0]}
        scale={1.678}
      >
        {clothMaterial}
      </mesh>
      {/* SKIN/FACE */}
      <mesh
        geometry={nodes.defaultMaterial020.geometry}
        // material={materials.Woman5Face}
        position={[-0.95, 0.174, 1.021]}
        rotation={[0, 0.328, 0]}
        scale={1.678}
      >
        {bodyMaterial}
      </mesh>
      {/* EYES */}
      <mesh
        geometry={nodes.defaultMaterial021.geometry}
        // material={materials.Woman5Eyes}
        position={[-0.95, 0.174, 1.021]}
        rotation={[0, 0.328, 0]}
        scale={1.678}
      >
        {bodyMaterial}
      </mesh>
    </group>
  );
}

useGLTF.preload("/looking_at_elthora-transformed.glb");
