"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 looking_at_elthora.glb --transform 
Files: looking_at_elthora.glb [18.55MB] > C:\Users\akila\OneDrive\Desktop\Elthora\looking_at_elthora-transformed.glb [1.85MB] (90%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

import {
  bodyMaterial,
  clothMaterial,
  furnitureMaterial,
} from "@/utils/materials";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/looking_at_elthora-transformed.glb");
  return (
    <group {...props} dispose={null}>
      {/* WOMAN 2 */}
      {/* CLOTH */}
      <mesh
        geometry={nodes.defaultMaterial022.geometry}
        // material={materials.Woman5Coat}
        position={[-0.95, 0.174, 1.021]}
        rotation={[0, 0.328, 0]}
        scale={1.678}
      >
        {clothMaterial}
      </mesh>
      {/* SKIN/FACE */}
      <mesh
        geometry={nodes.defaultMaterial020.geometry}
        // material={materials.Woman5Face}
        position={[-0.95, 0.174, 1.021]}
        rotation={[0, 0.328, 0]}
        scale={1.678}
      >
        {bodyMaterial}
      </mesh>
      {/* EYES */}
      <mesh
        geometry={nodes.defaultMaterial021.geometry}
        // material={materials.Woman5Eyes}
        position={[-0.95, 0.174, 1.021]}
        rotation={[0, 0.328, 0]}
        scale={1.678}
      >
        {bodyMaterial}
      </mesh>
    </group>
  );
}

useGLTF.preload("/looking_at_elthora-transformed.glb");
